### PR TITLE
Update runtime to 3.36

### PR DESCRIPTION
**Pull request by hfiguiere**

### CODE REVIEW

**Comment by hadess** [comment]
Did someone actually test this beyond the build succeeding? See https://github.com/flathub/org.glimpse_editor.Glimpse/issues/2

**Comment by ghost** [comment]
Confirming as the person that actually develops Glimpse Image Editor that I didn't know anything about this change until people started filing bug reports.

cc @bochecha as we need to take a close look at permissions for this repository. This shouldn't have been allowed to happen.

**Comment by AsciiWolf** [comment]
@TrechNex There is nothing wrong with this repo permissions. Everyone is free to send PRs and @bilelmoussaoui is a Flathub team member, he can merge them. However, I agree that all PRs should ideally be tested before they are merged.

**Comment by ghost** [comment]
If that’s the case, then what we’ve learned here is that so long as someone from Flathub says “yes” to it then anything goes. 🤦‍♂️

As you said, I’m disappointed this change was not tested beyond “it builds” and the beta branch was just totally ignored. I hope they do better in future.

I think ongoing we’re going to need to set up some notifications for this repo so that when changes are made we have some advanced warning. 🙂

This broke people’s installations, and expecting us to pick up the pieces each time that happens in future instead of reporting problems that have been found is decidedly not cool!

**Comment by hfiguiere** [comment]
As the original submitter of the PR here. I don't know why this escaped testing, possibly an oversight **and I apologize for this.** BTW, what's the upstream issue for that crash so one can track it down?

> If that’s the case, then what we’ve learned here is that so long as someone from Flathub says “yes” to it then anything goes. 🤦‍♂️
> 
> As you said, I’m disappointed this change was not tested beyond “it builds” and the beta branch was just totally ignored. I hope they do better in future.

Flathub beta are for beta of *upstream*, that's why it was not submitted.

> 
> I think ongoing we’re going to need to set up some notifications for this repo so that when changes are made we have some advanced warning. 🙂

You could be notified of new PR. Just click at the top on the "watch" button :

Screen Shot 2020-04-03 at 10 37 23 AM

But I guess what  I learned here is that the level of perfection expected by Glimpse-Editor will make me think twice before trying to help. I feel that the tone you took here reminded of a VP of engineering that would go yell and the software development team, but then break the build by pushing code at 5PM on a Friday and yell at an engineer over the week-end because the build broke and was not fixed (real life horror story).

**Comment by ghost** [comment]
I have watch and star set, which is why I was surprised not to get any notifications. :)

The reason I came over and made it clear this was a bad thing is because our project recommends Flathub as our primary installation channel. People are using this in actual production systems, and if the application stops working we get the blame. We weren't aware people could make changes without us approving it, which is why it came as a shock.

My apologies if you felt my tone was severe, but trust me when I say the tone people were taking with me was a *lot* more severe than that! :joy: 

I don't understand your point about the beta channel. Is it standard for it to be only used by us specifically?

**Comment by ghost** [comment]
Also as for the upstream bug, all the necessary links are pointed to from here: https://github.com/flathub/org.glimpse_editor.Glimpse/issues/2

I managed to turn around the fix within a few days, and with the help of others in the Glimpse project I've spent the last week or so testing it on Arch Linux, Elementary & other distros so I could reinstate your change yesterday.

**Comment by ghost** [comment]
Update: It seems the watch I set had "defaulted" to releases only. :man_facepalming: 
I've now updated that so I get an email for *all* conversations.

Hopefully that should prevent any future misunderstandings and mean that we can help coach people through changes to this repo in future. :+1:

**Pull request merged**
